config/routes.rb
Rails.application.routes.draw do

  resources :contatos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'sac', to: 'static_pages#sac'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'sessions/new'

  resources :users, only:[:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    has_many :contatoes
    has_secure_password

    VALID_EMAIL_REGEX = VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: {maximum: 50}
    validates :password, length: {minimum: 6}
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive:true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_logged_in_user
    unless user_signed_in?
      flash[:danger] = "Acesso negado"
      redirect_to entrar_path
    end

  end
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController

  before_action :require_logged_in_user
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = current_user.contatoes
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = current_user.contatoes.build(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = current_user.contatoes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :telefone)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to user_path(current_user.id)
    else
      flash.now[:danger] = 'Email e Senha inválidos'
      render 'new'
    end
  end

  def show

  end

  def destroy
    sign_out
    flash[:warning] = "Logout com sucesso"
    redirect_to entrar_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end

  def sac

  end

  def sobre

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Usuário cadastrado"
            redirect_to root_url
        else
            render 'new'
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def sign_out
        session.delete(:user_id)
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/_form.html.erb
<%= form_with(model: contato, local: true) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
<div class="row ">
  <div class="col-xs-12 text-center ">
    <h1>Meus contatos</h1>
    <h1><%= link_to "Novo Contato", new_contato_path, class: "btn btn-success text-center" %> </h1>
  </div>

  <div class="col-md-8 col-md-offset-2 col-xs-12 ">

    <table class="table table-striped ">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Telefone</th>
        <th colspan="2">
          Ações
        </th>
      </tr>
      </thead>

      <tbody>
        <% if @contatos.empty? %>
        <td colspan="4" class="text-center">
          <h3>Sem contatos cadastrados </h3>
        </td>
        <% end %>

        <% @contatos.each do |contato| %>
        <tr>
          <td class="mx-auto"><%= contato.nome %></td>
          <td><%= contato.telefone %></td>
          <td><%= link_to 'Show', contato, class: "btn btn-default"%></td>
          <td><%= link_to 'Edit', edit_contato_path(contato), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>

</div>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contato.telefone %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="">
        <div class="alert alert-danger">
            Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>
            <ul>
                <%= object.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
</small>

<nav>
  <ul>
    <li><%= link_to 'Sobre', sobre_path %></li>
    <li><%= link_to 'Contato', sac_path%></li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

    <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
        <% if !user_signed_in? %>
          <li class="active">
            <%= link_to 'Nova Conta', new_user_path %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li>
            <%= link_to 'Entrar', entrar_path %>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              bem vindo, <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Minha Pagina', current_user%>
              </li>
              <li>
                <%= link_to 'Editar', '#' %>
              </li>
              <li class="divider" role="separator"></li>
              <li>
                <%= link_to 'Sair', sair_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>

    </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    
    <div class="container">

        <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>


  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<ul>
  <li>numeros: 98 981007369</li>
</ul>

app/views/static_pages/index.html.erb
<div class='jumbotron'>
  <h1>Contact List</h1>

  <p>Gerencie seus contatos</p>

  <p>
    <%= link_to 'Ver contatos', contatos_path, class:"btn btn-default" %>
  </p>
</div>

app/views/static_pages/sac.html.erb
<h1>Contato</h1>

<ul>
  <li>numeros: 98 981007369</li>
</ul>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>Programa só pra aprender como usar Ruby on Rails</p>

app/views/users/new.html.erb
<div class="row">

    <div class="col-xs-12">
        <h1>Cadastre-se</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
        <%= form_for @user do |f| %>
            <%= render  "layouts/error_messages", object: f.object %>

            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
           
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %> 
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            
            <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<h1> Bem vindo, <%= current_user.name %></h1>

<div>
  <%= link_to "Ver seus contatos", contatos_path, class: "btn btn-primary" %>
</div>